### ISSUE TITLE
ERROR: Get https://docker.pkg.github.com/v2/olivia-ai/olivia/olivia/manifests/latest: no basic auth credentials

### ISSUE THREAD

**Issue by isathish** [olivia-ai/olivia#102]
First specify on which part this is related in the title with:
`ERROR: Get https://docker.pkg.github.com/v2/olivia-ai/olivia/olivia/manifests/latest: no basic auth credentials`

**Comment by hugolgst** [comment]
You need to log in using GitHub. Please see the GitHub documentation about that

**Comment by L3o-pold** [comment]
This link will help https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages

**Comment by hugolgst** [comment]
Thanks for refering it.
