### ISSUE TITLE
Doesn't recognise UK countries

### ISSUE THREAD

**Issue by iaicam** [olivia-ai/olivia#104]
**Describe the bug**
Doesn't recognise UK countries

**To Reproduce**
Ask what the capital of Scotland is.
Ask what the capital of England is.
Ask what the capital of the UK is.

**Expected behavior**
To tell me the capital of Scotland is Edinburgh, the capital of England is London and the capital of the UK is London

**Desktop (please complete the following information):**
Use website chat bot

**Comment by hugolgst** [comment]
Hello @iaicam, that is because they are not independent countries.
The dataset of countries is an open dataset and they are not part of it for this reason.

**Comment by hugolgst** [comment]
Sorry for the last comment, I did not read the question correctly.
I am going to investigate that problem, thanks a lot for the report.

**Comment by hugolgst** [comment]
So, I have looked inside the dataset and they are missing. I have no idea why they are missing but I am going to add them to the list.
