### ISSUE TITLE
Song recommendation

### ISSUE THREAD

**Issue by Amchuz** [olivia-ai/olivia#111]
**Describe what the module or intent should do** and **if this should be a module or an intent**
Please specify if you will implement this module or not.

Allow Olivia to recommend songs for users.
If you can explain the work of Olivia like, where to add the module and all, I would love to implement this module.

**Comment by hugolgst** [comment]
Hello!

The documentation explains that: https://docs.olivia-ai.org/modules.html#write-a-module

**Comment by Amchuz** [comment]
@hugolgst I would like to add this module. For that, I have some doubts :
1. I need a python file too for this. Where should I upload that ?
2. A dataset is needed for the songs. I am using The Million Song Dataset. How am I supposed to use it in Olivia ?
Hope you will reply soon.

**Comment by hugolgst** [comment]
Unfortunately, modules should be written in Golang. Olivia does not support other languages.

**Comment by Amchuz** [comment]
@hugolgst I will be writing the module in Golang. But can I import a python program into my Golang program ? If yes, where can I write my python program ?

**Comment by hugolgst** [comment]
I don’t know if it exists but if it does there will be a huge lack of performances, I don’t think that’s a good idea.

**Comment by Amchuz** [comment]
@hugolgst Ok. Thank you for your reply.

**Comment by hugolgst** [comment]
Sorry for that :/

**Comment by Amchuz** [comment]
@hugolgst No problem. I will try to add modules that does not affect the performance.
