### ISSUE TITLE
doc: how to run on docker

### ISSUE THREAD

**Issue by HenryHengZJ** [olivia-ai/olivia#112]
I am new to Docker and trying to run this awesome project on it.

So I have pulled the image from GitHub Packages:
`$ docker pull docker.pkg.github.com/olivia-ai/olivia/olivia:latest`

Then start it
`$ docker run -d -p 8080:8080 docker.pkg.github.com/olivia-ai/olivia/olivia:latest`

But when I try to run 
`$ docker container ls`

I didn't see anything there and not sure how to use the command:
`$ docker-compose up`

**Comment by hugolgst** [comment]
Are you sure you did pull the image correctly?

**Comment by HenryHengZJ** [comment]
When I used the command:
`docker images`
I can see the repo, tag, ImageID and etc.

**Comment by hugolgst** [comment]
Is there an error when you run the image?

**Comment by HenryHengZJ** [comment]
There is some problem with my docker installation. For now I chose to go for git installation instead.
