### ISSUE TITLE
Installation/setup issues

### ISSUE THREAD

**Issue by isakcodes** [olivia-ai/olivia#123]
Hi! Would really appreciate some help with setting up the project. I have got it running on my machine with docker, but I just get a 404 on localhost:8080

**Describe the bug**
I get a 404 Page not found error starting Olivia with the yml file using `docker-compose up`

![image](https://user-images.githubusercontent.com/61279302/83661041-dfcb3b80-a5c5-11ea-9c4c-854b74929982.png)

**To Reproduce**
Follow the installation instructions in the readme

**Expected behavior**
For it to start the frontend. It seems it starts but gives a 404. Not sure how to fix.

**Desktop (please complete the following information):**
 - OS: Mac High Sierra 10.13.6
 - Browser: Brave, Chrome, Safari
 - Version: 3

**Additional context**
Console print below. It mentions a warning about VUE_APP_URL, however I haven't been able to reproduce it again. Might have something to do with it..

```
➜  docker-compose up
Creating network "olivia_default" with the default driver
Building olivia-ai.org
Step 1/10 : FROM golang:latest
latest: Pulling from library/golang
376057ac6fa1: Already exists
5a63a0a859d8: Already exists
496548a8c952: Already exists
2adae3950d4d: Already exists
039b991354af: Already exists
6b823afb12d9: Already exists
30b9d62bd869: Already exists
Digest: sha256:4d58164df51901679307e547ffed19837e63a1d1b9ed80453b8d88749b6033f4
Status: Downloaded newer image for golang:latest
 ---> 05feda542433
Step 2/10 : LABEL maintainer="Hugo Lageneste <hugo@olivia-ai.org>"
 ---> Running in 2e2ee458d257
Removing intermediate container 2e2ee458d257
 ---> f453eb20bc61
Step 3/10 : WORKDIR /app
 ---> Running in 4038ef62e966
Removing intermediate container 4038ef62e966
 ---> db2b5a8b7e8e
Step 4/10 : COPY go.mod go.sum ./
 ---> 46da89293ac4
Step 5/10 : RUN go mod download
 ---> Running in 79996758c044
Removing intermediate container 79996758c044
 ---> 3b978032a205
Step 6/10 : COPY . .
 ---> c84e79163408
Step 7/10 : RUN go test
 ---> Running in c1e6c7d0f115
?   	github.com/olivia-ai/olivia	[no test files]
Removing intermediate container c1e6c7d0f115
 ---> 48ca46a5915c
Step 8/10 : RUN go build -o main .
 ---> Running in 0ce9a4d78ed8
Removing intermediate container 0ce9a4d78ed8
 ---> 76445f475d26
Step 9/10 : EXPOSE $PORT
 ---> Running in 52a368becb2c
Removing intermediate container 52a368becb2c
 ---> 46d43046d8ae
Step 10/10 : CMD ["./main", "-port=$PORT"]
 ---> Running in 56630341e00f
Removing intermediate container 56630341e00f
 ---> fe6e19a1d981
[Warning] One or more build-args [VUE_APP_URL] were not consumed
Successfully built fe6e19a1d981
Successfully tagged docker.pkg.github.com/olivia-ai/olivia-ai.org/olivia-ai.org:latest
WARNING: Image for service olivia-ai.org was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating olivia_olivia_1        ... done
Creating olivia_olivia-ai.org_1 ... done
Attaching to olivia_olivia_1, olivia_olivia-ai.org_1
olivia_1         |        _ _       _
olivia_1         |   ___ | (_)_   _(_) __ _
olivia_1         |  / _ \| | \ \ / / |/ _` |
olivia_1         | | (_) | | |\ V /| | (_| |
olivia_1         |  \___/|_|_| \_/ |_|\__,_|
olivia_1         |
olivia_1         | hey
olivia_1         | Your authentication token is: 29568e57b2cf0fa02478ac22e93de87a783744d2b3ab0b54a6d3db62cbf7
olivia_1         | Save it, you won't be able to get it again unless you generate a new one.
olivia_1         |
olivia-ai.org_1  |        _ _       _
olivia-ai.org_1  |   ___ | (_)_   _(_) __ _
olivia-ai.org_1  |  / _ \| | \ \ / / |/ _` |
olivia-ai.org_1  | | (_) | | |\ V /| | (_| |
olivia-ai.org_1  |  \___/|_|_| \_/ |_|\__,_|
olivia-ai.org_1  |
olivia-ai.org_1  | Loading the neural network from res/locales/en/training.json
olivia-ai.org_1  | Loading the neural network from res/locales/de/training.json
olivia-ai.org_1  | Loading the neural network from res/locales/fr/training.json
olivia-ai.org_1  | Loading the neural network from res/locales/es/training.json
olivia-ai.org_1  | Loading the neural network from res/locales/ca/training.json
olivia-ai.org_1  | Loading the neural network from res/locales/it/training.json
olivia-ai.org_1  | Loading the neural network from res/locales/tr/training.json
29568e57b2cf0fa02478ac22e93de87a783744d2b3ab0b54a6d3db62cbf7
olivia-ai.org_1  | Loading the neural network from res/locales/nl/training.json
olivia-ai.org_1  |
olivia-ai.org_1  | Server listening on the port 80...
olivia_1         | Loading the neural network from res/locales/en/training.json
olivia_1         | Loading the neural network from res/locales/de/training.json
olivia_1         | Loading the neural network from res/locales/fr/training.json
olivia_1         | Loading the neural network from res/locales/es/training.json
olivia_1         | Loading the neural network from res/locales/ca/training.json
olivia_1         | Loading the neural network from res/locales/it/training.json
olivia_1         | Loading the neural network from res/locales/tr/training.json
olivia_1         | Loading the neural network from res/locales/nl/training.json
olivia_1         |
olivia_1         | Server listening on the port 8080...
```

**Comment by hugolgst** [comment]
Your packages aren't updated, please execute `docker-compose pull`

**Comment by isakcodes** [comment]
Thanks for the help! Now I got the same error as #119 .

**Comment by hugolgst** [comment]
I thought it would be this, I am going to find a solution quickly.

**Comment by hugolgst** [comment]
The issue has been fixed, execute `docker-compose pull` again and it should be fine.

**Comment by at-maonv** [comment]
Hi @hugolgst 
I tried to use  **docker build -t front .** and **docker run -p 8080:8080 front** but I just got an error.
[+] Building 10.1s (9/11)
 => [internal] load build definition from Dockerfile                                                                                                                               0.1s
 => => transferring dockerfile: 261B                                                                                                                                               0.0s
 => [internal] load .dockerignore                                                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/node:lts-alpine                                                                                                                 1.5s
 => [1/7] FROM docker.io/library/node:lts-alpine@sha256:0a6a21d28509f56155007444075ef4fdd36eef0a97924623cb641d3766e3b8d3                                                           0.0s
 => => resolve docker.io/library/node:lts-alpine@sha256:0a6a21d28509f56155007444075ef4fdd36eef0a97924623cb641d3766e3b8d3                                                           0.0s
 => [internal] load build context                                                                                                                                                  6.4s
 => => transferring context: 4.17MB                                                                                                                                                6.1s
 => CACHED [2/7] RUN npm install -g http-server                                                                                                                                    0.0s
 => CACHED [3/7] WORKDIR /app                                                                                                                                                      0.0s
 => [4/7] COPY package*.json ./                                                                                                                                                    0.6s
 => ERROR [5/7] RUN npm ci                                                                                                                                                         1.4s
------
 > [5/7] RUN npm ci:
#9 1.248 npm ERR! code ENOENT
#9 1.249 npm ERR! syscall open
#9 1.251 npm ERR! path /app/package.json
#9 1.254 npm ERR! errno -2
#9 1.262 npm ERR! enoent ENOENT: no such file or directory, open '/app/package.json'
#9 1.263 npm ERR! enoent This is related to npm not being able to find a file.
#9 1.263 npm ERR! enoent
#9 1.302
#9 1.302 npm ERR! A complete log of this run can be found in:
#9 1.303 npm ERR!     /root/.npm/_logs/2021-04-02T02_34_14_004Z-debug.log
------

Please help me to check it.
Thank you so much!
