### ISSUE TITLE
provide examples

### ISSUE THREAD

**Issue by marshonhuckleberry** [olivia-ai/olivia#125]

**Comment by hugolgst** [comment]
What do I suggest for what? Could you be more precise please?

**Comment by marshonhuckleberry** [comment]
not my fault had selected some random option wich writed things for me, i edited the issue now. i mean this code also needs a chat example with the bot

**Comment by hugolgst** [comment]
you can find these examples in the code, you mean in the README?

**Comment by marshonhuckleberry** [comment]
i mean a text file containing an example chat

**Comment by hugolgst** [comment]
Why we should do that? intents.json already contains that

**Comment by marshonhuckleberry** [comment]
where is intents.json located?

**Comment by hugolgst** [comment]
res/`name of the locale`/intents.json depending on the language

**Comment by marshonhuckleberry** [comment]
oh, that's a question-answer bot, i thought it was a more intelligent bot (learning, understanding) that is why i asked for examples but i guess its some sort of practical bot, i tried the online chat demo but robot gave irrelevant answers for some reason

**Comment by marshonhuckleberry** [comment]
a little example can be seen here: https://docs.olivia-ai.org/console.html#installation

**Comment by hugolgst** [comment]
It is learning and it is understanding

**Comment by hugolgst** [comment]
If you want examples, you can watch the YouTube preview.
