### ISSUE TITLE
Issue with pulling docker images and building from source

### ISSUE THREAD

**Issue by milouk** [olivia-ai/olivia#128]
I can't seem to be able to build the project both with the docker nor the git way

**Describe the bug**

* Docker method

Whenever I type the command `docker pull docker.pkg.github.com/olivia-ai/olivia/olivia:latest` I get `Error response from daemon: Get https://docker.pkg.github.com/v2/olivia-ai/olivia/olivia/manifests/latest: no basic auth credentials`

* GitHub Method

If I clone the repo as mentioned in the README, install the go dependencies, the run it and navigate to `localhost:8080` I get a `404 page not found` error.

P.S using `docker-compose up` results to the same error as the one in the Docker method

**To Reproduce**
1. Follow Docker installation instructions
2. Follow GitHub installation instructions
3. Poof

**Expected behavior**
An expected behavior would be to either build the project successfully using docker and/or with executing the bootstrap `main.go` file

**Desktop (please complete the following information):**
 - OS: Linux Mint, MacOS, Ubuntu Server
 - Browser: Chrome
 - Version 83.0.4103.106 (Official Build) (64-bit)

**Additional Context**

By the way what do I need the authentication token for and how am I supposed to use it? Does it somehow has to do with the aforementioned `no basic auth credentials` ?

**Comment by hugolgst** [comment]
Please see #102.

**Comment by milouk** [comment]
I managed to fix it. However, it still is not clear after seeing #102. I would suggest having a brief mention in the README.

**Comment by hugolgst** [comment]
Great suggestion, I will do that after I come back from vacation. Thanks!

**Comment by milouk** [comment]
No problem Hugo, enjoy your vacations :)
