### ISSUE TITLE
Implementation in a Telegram bot

### ISSUE THREAD

**Issue by x0rzkov** [olivia-ai/olivia#134]
Hi guys,

Hope you are all well !

I was looking for some implementation of AI chatbot golang and found your project `olivia`.

And, I am developing a multibot for telegram based on go plugins: https://github.com/paper2code/telegram-multibot

So I was wondering how can I integrate `olivia` as a plugin.

Do you have any insights or advices for such integration ?

Thanks in advance.

Cheers,
X

**Comment by hugolgst** [comment]
Hello,

First of all let me tell you that I am glad that you want to use Olivia.
Then, the source code of Olivia serves a WebSocket on which you can connect.
I will let you check the code of https://github.com/olivia-ai/olivia-kit-go which is a wrapper on the WebSocket of Olivia and you can interact with the chatbot from it.
Do not hesitate to ask any question on issues if you have some.

Thanks,
Hugo

**Comment by x0rzkov** [comment]
Thanks @hugolgst 

How do you train olivia on specific questions/answers ?

I already made telegram QA bot for Arxiv.org papers https://github.com/paper2code/telegram-qa-with-arxiv-papers where I ingested the dataset with the help of the [haystack](https://github.com/deepset-ai/haystack) framework.

Is it possible to load such models into `olivia` ?

**Comment by hugolgst** [comment]
Olivia uses its own dataset but you can of course customize it and specify it in the server.
However, you will need to host a server.
Here is a link to the related page on the documentation: https://docs.olivia-ai.org/intents.html#adding-via-the-file-system

**Comment by x0rzkov** [comment]
Btw, I tried the [demo](https://olivia-ai.org/chat) with some texts like
`what is arxiv ?`
`what time is it ?`

she kept replying

`My job is to make you feel like everything is okay.`

Did I do something wrong ?

**Comment by hugolgst** [comment]
Yes indeed the official version online have a really small dataset thus she replies wrong to a lot of requests but with a bigger dataset it should reply right.
