### ISSUE TITLE
Error When Trying to Chat with Bot using Olivia Console

### ISSUE THREAD

**Issue by ad3n** [olivia-ai/olivia#153]
![Screenshot from 2021-02-22 22-38-05](https://user-images.githubusercontent.com/7464920/108731120-d1132300-755e-11eb-89d7-5f1d47fd7606.png)

I clone from master branch

**Comment by surya4crowde** [comment]
Hi @hugolgst I checked and I found the `classes` have 53 subset but the `predict` only have 33

**Comment by hugolgst** [comment]
Just to know how to reproduce the bug, have you launched the App via Docker?

**Comment by ad3n** [comment]
@hugolgst i just clone the master branch and install without docker

**Comment by hugolgst** [comment]
Could you send the history of commands you're executing ?

**Comment by surya4crowde** [comment]
![Screenshot from 2021-02-24 19-46-29](https://user-images.githubusercontent.com/70564773/109002750-2f641100-76d9-11eb-9ee1-4e2d9a8cf378.png)

Hello @hugolgst, i just run `go run main.go` in both of `olivia` and `olivia-console` like screenshot above

**Comment by adevroy** [comment]
You need to delete the training file in your locale and then retrain. The training files checked into github have issues.

**Comment by hugolgst** [comment]
Yep that's what I saw, I also added another condition in order to avoid such problems.
Gonna push tonight

**Comment by surya4crowde** [comment]
Thank you @adevroy fix
