### ISSUE TITLE
Problem with upper case letters and punctuation

### ISSUE THREAD

**Issue by ananagame** [olivia-ai/olivia#40]
![](https://i.imgur.com/RMy76Wi.png)

Olivia don't understand when I write "Who are you ?" instead of "who are you"

**Comment by ananagame** [comment]
Correct this issue by generating a new model and adding test to verify that the model isn't answering wrong

**Comment by Songkeys** [comment]
Is this resolved? I don't see that...

![image](https://user-images.githubusercontent.com/22665058/59590896-961ce300-911f-11e9-9ac2-18c1dd67b827.png)

**Comment by ananagame** [comment]
Yes it is, that’s Hi another issue I can’t explain
