### ISSUE TITLE
Olivia listening but: 404 page not found

### ISSUE THREAD

**Issue by gismo07** [olivia-ai/olivia#41]
I've installed Olivia on my windows system following the documentation.
However, if I launch it the browser only outputs: 404 page not found

**Comment by ananagame** [comment]
Which page are you trying to reach?

**Comment by gismo07** [comment]
After run `go run main.go` the console output is: Listening on the port 8080.
So I try to open localhost:8080. Or am I wrong?

**Comment by ananagame** [comment]
Alright but to chat with Olivia you need to send your POST request to api/response like said [here](https://docs.olivia-ai.org/#how-to-use)

**Comment by gismo07** [comment]
Ok sorry ... I was not aware, that this is a REST api "only". 
The demo was a bit missleading

**Comment by ananagame** [comment]
I will review the doc later

**Comment by prologic** [comment]
Can we borrow/re-use the UI off the original project that inspired this version?

**Comment by ananagame** [comment]
I used Buefy which is Bulma for Vue.js so of course you can!

**Comment by prologic** [comment]
I actually meant to reuse/borrow the UI  code directly and embed it and serve it up.

**Comment by ananagame** [comment]
Oh yes you can

**Comment by prologic** [comment]
Any change we can embed it via `git submodule` and serve it up here? With permission of the Leon author ofc :)
