### ISSUE TITLE
own module not recogniced

### ISSUE THREAD

**Issue by gismo07** [olivia-ai/olivia#42]
I've followed the tutorial to create a own simple module:

```
package modules

import (
	"fmt"
)

func init() {
	RegisterModule(Module{
		Tag: "gismo",
		Patterns: []string{
			"Who is gismo",
		},
		Responses: []string{
			"Gismo is my %s",
		},
		Replacer: MyModuleReplacer,
	})
}

func MyModuleReplacer(entry, response string) string {
    return fmt.Sprintf(response, "cat")
}
```

But the module is never triggerd. Is there any additional step required?

**Comment by ananagame** [comment]
Where did you put this file?

**Comment by gismo07** [comment]
It's located here: olivia/modules/gismo.go

**Comment by ananagame** [comment]
Oh I know, my fault I didn't mention this in the doc. If there's already a save (res/training.json) you need to remove it

**Comment by gismo07** [comment]
Hmm now it's training but the module is still not called.
I changed the sentence in the module to `Play gismo`, the console output is:

> "play gismo"
>   ▫︎ good - 0.5945061808473607
>   ▫︎ goodbye - 0.2765635864383791
>   ▫︎ identity - 0.06918056345808914
>   ▫︎ math - 0.06048480037064531
>   ▫︎ action - 0.053688664966205384

**Comment by ananagame** [comment]
Let me see the code please

**Comment by gismo07** [comment]
What I've done:

- Gismo module:

``` go
package modules

import (
	"fmt"
)

func init() {
	RegisterModule(Module{
		Tag: "gismo",
		Patterns: []string{
			"Play gismo",
			"Who is gimso",
			"Where is gismo"
		},
		Responses: []string{
			"Gismo is my %s",
		},
		Replacer: MyModuleReplacer,
	})
}

func MyModuleReplacer(entry, response string) string {
	return fmt.Sprintf(response, "cat")
}

```

- deleted the `res/training.json` file
- ask olivia with `curl -X POST "localhost:8080/api/response" --data "sentence=Where is gismo" --data "authorId=81278329034"`

The response:

> {"content":"I'm trying to do my best but I don't understand","tag":"don't understand"}

Log:

> "where is gismo"
>   ▫︎ random_number - 0.3153563090202687
>   ▫︎ math - 0.16555582188794699
>   ▫︎ city - 0.1607288843344628
>   ▫︎ capital - 0.14783259948476532
>   ▫︎ women - 0.1277046160367534
>   ▫︎ job - 0.10882489275726054
>   ▫︎ hello - 0.08043071245798913
>   ▫︎ currency - 0.0751861898952632
>   ▫︎ identity - 0.06419732512193507

**Comment by ananagame** [comment]
You forgot a comma at the end of "Where is gismo"

**Comment by gismo07** [comment]
Ok added that, but nothing changed

**Comment by ananagame** [comment]
It worked for me, try to delete again and restart the api

**Comment by gismo07** [comment]
I tested something else: I changed the text of the random module.
However nothing changed at the olivia output.

Is this maybe related to some cache?

**Comment by ananagame** [comment]
The only cache is the save of the model, when you delete it the model must get allo the intents and the modules. I’m trying to figure out what you did wrong because it is working perfectly for me🤔

**Comment by gismo07** [comment]
I found the solution:
I had to add the module to `src\github.com\olivia-ai\olivia\modules` not to the cloned `src\olivia\modules`.

Maybe also add that to the documentation ;-)
But now its working - really cool!

**Comment by ananagame** [comment]
Sure I add this to the TODO list
