### ISSUE TITLE
Feature comparison with LeonAI

### ISSUE THREAD

**Issue by prologic** [olivia-ai/olivia#43]
It would be nice to do a feature comparison with [LeonAI](https://github.com/leon-ai/leon) of which inspired this project. A Roadmap of where you want to take this would be nice too for contributors to have some kind of "grand vision".

**Comment by ananagame** [comment]
The goal is not to do the same as Leon, if you want to see me to do list you can use GitHub projects

**Comment by prologic** [comment]
The two projects listed don't realy say much about your long-term goals?

**Comment by ananagame** [comment]
No, because I don't have long-term goals. I just want Olivia to become better and better with the time, and we'll see what to implement in due course

**Comment by prologic** [comment]
Hmmm that doesn't really help newcomers to this project. I'd encourage you to at least write a few bullet points down in the README. You've already made it clear you won't want it to be feature-complete with Leon; but then again your project is inspired/based on it? Forgive me for being confused :)

**Comment by ananagame** [comment]
The author of Leon has helped me a lot on many points and I was inspired with Olivia on his project so to thanks him I wrote this on the README

**Comment by ananagame** [comment]
For newcomers I see, maybe later I will add some goals!

**Comment by prologic** [comment]
To be clear; I'm a fellow developer like you; and I Love Go! I intend to try out both Oliver and Leon; buat at this stage I will more than likely spin up Leon in my production environment because it is more feature complete and mature.

That being said however; I have a **strong** preference to towards services/apps written in Go (*than Python or NodeJS or PHP*) because typically the resource costs are smaller and the performance is usually better.

I also have a bias towards Dockerizing everything to make packaging and deployments easier.

**Comment by ananagame** [comment]
Sure I understand Leon is way more complete than Olivia. Olivia now have her structure with modules so you can easily add yours to make a PR or add some intents

**Comment by ananagame** [comment]
With the enthusiasm around Olivia I hope there will be new ideas of contributions :)

**Comment by prologic** [comment]
Understood  :) -- What I _was_ after in the first place was some high-level things like:

- Does Olivia have or intend to have an NLP?
- Does Olivia have or intend to have an TTS?
- Does Olivia have or intend to have an SST?

These are important aspects and core features that extensible modules can then build upon IHMO.

**Comment by ananagame** [comment]
Olivia has already the three of them

**Comment by prologic** [comment]
> With the enthusiasm around Olivia I hope there will be new ideas of contributions :)

Me too : ) This is an important/exciting project to complete with the likes of Alexa, Siri and others. Self-hosting and OSS is becoming more and more important!

**Comment by ananagame** [comment]
The Go part is only the neural network and all the NLP, the STT and TTS are part of the Web app [c.f](https://github.com/olivia-ai/olivia-ai.org)

**Comment by prologic** [comment]
> Olivia has already the three of them

May I ask that you file a separate issue to document them, how they work at a high-level and how to contribute to their design/implementation (*if not externally provided by libraries*)?

**Comment by ananagame** [comment]
Sure, my next job is to document the Web app to make it installable and configurable by everyone

**Comment by prologic** [comment]
Sounds good! Also this discussion has already partly documented a "feature comparison" as well as  "vision" of sorts. Just say'n  :)

**Comment by ananagame** [comment]
I've created projects to add goals and todos :) https://github.com/orgs/olivia-ai/projects
