### ISSUE TITLE
doesn't remember my name 🤷‍♂️

### ISSUE THREAD

**Issue by avierr** [olivia-ai/olivia#46]
If i go to https://olivia-ai.org/chat
and say something like: my name is Avi
and then ask it: what is my name? it replies "I'm Olivia" 

even really old bots like ALICE get this simple thing right,
https://pandorabots.com/pandora/talk?botid=b8d616e35e36e881

Is a fix possible?

**Comment by ananagame** [comment]
She does not remember your name because this feature has not been implemented yet

**Comment by ananagame** [comment]
But I can add this to the project :)

**Comment by natzar** [comment]
Before the neural network is trained, might be good to add AIML support, because it's very limited,  right now. Have experiene with chatbots, want to help.

**Comment by ananagame** [comment]
All done! 
![](https://i.imgur.com/CcOfLFY.png)

**Comment by avierr** [comment]
Wohoo! Thanks!

**Comment by ananagame** [comment]
All the information about the user are in the app cache and stored in the client's browser, so I don't keep any data!
