### ISSUE TITLE
It may be worth limiting the size of a user's message.

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [olivia-ai/olivia#47]
Sending an absurdly long message (gibberish or not) results in a correspondingly absurd wait time as Olivia tries to understand what you're saying :) Though she does eventually manage to figure it out!

![image](https://user-images.githubusercontent.com/19352442/59781183-4d813900-9289-11e9-87ab-eabea2c6cc25.png)

Since it's a chat application, it may be worth limiting the user input to a certain reasonable number of characters, like 500 max maybe (I'm not sure what a good number would be).

This likely won't be an issue in the general use case, but I enjoy breaking things and figured I'd chime in, lol.

**Comment by ananagame** [comment]
Very good point, I’ll limite the size to 500

**Comment by ananagame** [comment]
All done! Thanks :)

**Comment by AleksandrHovhannisyan** [comment]
No problem! Though I was thinking more along the lines of preventing the user from entering a large message in the first place by imposing a character limit on the text input widget (basically ignoring input if the size of the entered message is already 500 chars). It may even be good to show a little counter for how many characters are left, sort of like on Twitter. (Just throwing ideas/suggestions out there! :D)

That way, the app doesn't lag/Olivia doesn't take a long time to respond. Since you're hosting it on Heroku, though, I guess it's (maybe?) not a big deal because it's not your personal server handling it :)
