### ISSUE TITLE
Olivia stopped answering after a few words

### ISSUE THREAD

**Issue by DuAell** [olivia-ai/olivia#51]
![image](https://user-images.githubusercontent.com/708163/60345117-8ff8f300-99b8-11e9-93af-4284e17134b6.png)

**Comment by ananagame** [comment]
Hello, thanks for the report, do you have any errors in the console?

**Comment by DuAell** [comment]
I've done this test on https://olivia-ai.org. Didn't seen any console there.

**Comment by ananagame** [comment]
Perhaps the application was restarting
