### ISSUE TITLE
Support for audo blobs?

### ISSUE THREAD

**Issue by Xeoncross** [olivia-ai/olivia#52]
leon supports [processing WAV files locally into text](https://github.com/leon-ai/leon/blob/develop/server/src/stt/deepspeech/parser.js). Does olivia plan on adding support for audio blobs/streams like WAV/PCM?

I'm a little concerned you're only going to support _online_ usage [by sending data to Google](https://github.com/olivia-ai/olivia-ai.org/blob/master/src/views/Chat.vue#L80) by using the `SpeechRecognition` API.

**Comment by ananagame** [comment]
The goal is not to do the same things as leon, and for the SpeechRecognition API you're not forced to use it and it is more easy to implement than an offline support :)

**Comment by hugolgst** [comment]
I am going to close this issue.
