### ISSUE TITLE
analysis: punctuation allowed in training

### ISSUE THREAD

**Issue by aitva** [olivia-ai/olivia#63]
Hi ! Thank you for Olivia, I had a look at the sources and it is a great piece of software. :clap:

I had trouble using the `name getter` tag and I noticed that upper case letters and punctuation are removed from user inputs, but not from the training data. Removing punctuation in `modules/name.go` fixes the problem.

I think `analysis.Organize` should use `analysis.NewSentence` to standardize the input for the neural network. I can make a pull request if you want.

**Comment by ananagame** [comment]
I will fix this later, thanks a lot for the issue!
