### ISSUE TITLE
Linux console client for Olivia

### ISSUE THREAD

**Issue by NerdDoc** [olivia-ai/olivia#78]
I created linux console client for Olivia - you can find it by link (https://github.com/NerdDoc/Olivia-CC)

**Comment by hugolgst** [comment]
Wow, that's amazing!
Thanks a lot for this resource.

Maybe we could add it to the Olivia Organization!

**Comment by NerdDoc** [comment]
Hello! Ofcourse you can add it to Olivia Organization. Is there any discussion channel for Olivia, i would like to connect?

**Comment by hugolgst** [comment]
No, there isn't one yet.
I'm hesitating to create one and on which platform.

**Comment by NerdDoc** [comment]
maybe Discord. For now a day i don't see any differences between platforms.

**Comment by hugolgst** [comment]
Here it is! 
https://discord.gg/bXv2Wd
