### ISSUE TITLE
intents/modules: add jokes

### ISSUE THREAD

**Issue by hugolgst** [olivia-ai/olivia#80]
Create a joke module or intent.
I'm not sure yet if this should be a module which will retrieve jokes from an API (not necessary I think) or simply an intent.
Opened for contributors.

**Comment by cvhariharan** [comment]
Hi, is this still open? I would like to give this a go. I am thinking of adding a module to make an API request and return a joke.

**Comment by hugolgst** [comment]
Hello, of course it is still open!

**Comment by cvhariharan** [comment]
Also, I wanted to add an env variable and I see that even though there is an .env file, it is not being used in the dockerfile. So, should I also update the dockerfile to use the env file or for the time being, should I add the env variable to the dockerfile itself.

**Comment by hugolgst** [comment]
You can make a PR for that yes
